config/routes.rb
Bartimes::Application.routes.draw do
  resources :opentimes

  resources :bars
  

end

app/models/bar.rb
class Bar < ActiveRecord::Base

has_many :opentimes

end

app/models/opentime.rb
class Opentime < ActiveRecord::Base

belongs_to :bar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  # GET /bars
  # GET /bars.json
  def index
    if params[:days]
      @bars = Opentime.where(:days => params[:days]).map(&:bar).uniq
    else
      @bars = Bar.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bars }
    end
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, :notice => 'Bar was successfully created.' }
        format.json { render :json => @bar, :status => :created, :location => @bar }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, :notice => 'Bar was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :ok }
    end
  end
end

app/controllers/opentimes_controller.rb
class OpentimesController < ApplicationController
  # GET /opentimes
  # GET /opentimes.json
  def index
    if params[:days].blank?
      @opentimes = Opentime.all
    else
      @opentimes = Opentime.where(:days => params[:days])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @opentimes }
    end
  end

  # GET /opentimes/1
  # GET /opentimes/1.json
  def show
    @opentime = Opentime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @opentime }
    end
  end

  # GET /opentimes/new
  # GET /opentimes/new.json
  def new
    @opentime = Opentime.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @opentime }
    end
  end

  # GET /opentimes/1/edit
  def edit
    @opentime = Opentime.find(params[:id])
  end

  # POST /opentimes
  # POST /opentimes.json
  def create
    @opentime = Opentime.new(params[:opentime])

    respond_to do |format|
      if @opentime.save
        format.html { redirect_to @opentime, :notice => 'Opentime was successfully created.' }
        format.json { render :json => @opentime, :status => :created, :location => @opentime }
      else
        format.html { render :action => "new" }
        format.json { render :json => @opentime.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /opentimes/1
  # PUT /opentimes/1.json
  def update
    @opentime = Opentime.find(params[:id])

    respond_to do |format|
      if @opentime.update_attributes(params[:opentime])
        format.html { redirect_to @opentime, :notice => 'Opentime was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @opentime.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /opentimes/1
  # DELETE /opentimes/1.json
  def destroy
    @opentime = Opentime.find(params[:id])
    @opentime.destroy

    respond_to do |format|
      format.html { redirect_to opentimes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/opentimes_helper.rb
module OpentimesHelper
end

app/views/bars/_form.html.haml
= form_for(@bar) do |f|
  - if @bar.errors.any?
    #error_explanation
      %h2
        = pluralize(@bar.errors.count, "error")
        prohibited this bar from being saved:
      %ul
        - @bar.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :area
    %br/
    = f.text_field :area
  .field
    = f.label :type
    %br/
    = f.text_field :type
  .field
    = f.label :address
    %br/
    = f.text_field :address
  .field
    = f.label :phone
    %br/
    = f.text_field :phone
  .field
    = f.label :website
    %br/
    = f.text_field :website
  .actions
    = f.submit

app/views/bars/barsonmap.haml
<!DOCTYPE html "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "content-type"}/
    %title Google Maps JavaScript API Example
    %script{:src => "http://maps.google.com/maps?file=api&v=2&key=abcdefg&sensor=true_or_false", :type => "text/javascript"}
    :javascript
      function initialize() {
        if (GBrowserIsCompatible()) {
          var map = new GMap2(document.getElementById("map_canvas"));
          map.setCenter(new GLatLng(37.4419, -122.1419), 13);
          map.setUIToDefault();
        }
      }

        %body{:onload => "initialize()", :onunload => "GUnload()"}
    #map_canvas{:style => "width: 500px; height: 300px"}

app/views/bars/edit.html.haml
%h1 Editing bar
= render 'form'
- @bar.opentimes.each do |time|
  %div
    = time.inspect
    = link_to 'Edit', edit_opentime_path(time)
= link_to 'New', new_opentime_path
= link_to 'Show', @bar
|
\#{link_to 'Back', bars_path}

app/views/bars/index.html.haml
%script{:src => "http://maps.google.com/maps?file=api&v=2&key=AIzaSyCoCzynRPhG9DYNrGLF3V_M6U6emE8bPyM&sensor=true_or_false", :type => "text/javascript"}
:javascript
  function initialize() {
  if (GBrowserIsCompatible()) {
    var map = new GMap2(document.getElementById("map_canvas"));
    map.setCenter(new GLatLng(37.4419, -122.1419), 13);
    map.setUIToDefault();
  }

%body{:onload => "initialize()", :onunload => "GUnload()"}
  #map_canvas{:style => "width: 500px; height: 300px"}
  
%h1 Listing bars
%table
  %tr
    %th Name
    %th Area
    %th Type
    %th Address
    %th Phone
    %th Website
    %th
    %th
    %th
  - @bars.each do |bar|
    %tr
      %td= bar.name
      %td= bar.area
      %td= bar.type
      %td= bar.address
      %td= bar.phone
      %td= bar.website
      %td= link_to 'Show', bar
      %td= link_to 'Edit', edit_bar_path(bar)
      %td= link_to 'Destroy', bar, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Bar', new_bar_path

app/views/bars/new.html.haml
%h1 New bar
= render 'form'
= link_to 'Back', bars_path

app/views/bars/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @bar.name
%p
  %b Area:
  = @bar.area
%p
  %b Type:
  = @bar.type
%p
  %b Address:
  = @bar.address
%p
  %b Phone:
  = @bar.phone
%p
  %b Website:
  = @bar.website
- @bar.opentimes.sort_by(&:days).each do |time|
  %div
    = time.days
    \: #{time.start}-#{time.finish}
= link_to 'Edit', edit_bar_path(@bar)
|
\#{link_to 'Back', bars_path}

app/views/layouts/application.haml
!!!
%html
  %head
    %title Bartimes
    <link rel='stylesheet' type='text/css' href="/stylesheets/style.css" %>
    \#{stylesheet_link_tag    "application"}
    \#{javascript_include_tag "application"}
    \#{csrf_meta_tags}
    
    
  %body
    = yield

app/views/layouts/applicationold.html.haml
!!!
%html
  %head
    %title Bartimes
    <link rel='stylesheet' type='text/css' href="/stylesheets/style.css" %>
    \#{stylesheet_link_tag    "application"}
    \#{javascript_include_tag "application"}
    \#{csrf_meta_tags}
  %body
    = yield

app/views/opentimes/_form.html.haml
= form_for(@opentime) do |f|
  - if @opentime.errors.any?
    #error_explanation
      %h2
        = pluralize(@opentime.errors.count, "error")
        prohibited this opentime from being saved:
      %ul
        - @opentime.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :bar_id
    %br/
    = f.number_field :bar_id
  .field
    = f.label :days
    %br/
    = f.text_field :days
  .field
    = f.label :start
    %br/
    = f.text_field :start
  .field
    = f.label :finish
    %br/
    = f.text_field :finish
  .field
    = f.label :day_id
    %br/
    = f.text_field :day_id
  .actions
    = f.submit

app/views/opentimes/edit.html.haml
%h1 Editing opentime
= render 'form'
= link_to 'Show', @opentime
|
\#{link_to 'Back', opentimes_path}

app/views/opentimes/index.html.haml
%h1 Listing opentimes
%table
  %tr
    %th Bar
    %th Days
    %th Start
    %th Finish
    %th
    %th
    %th
  - @opentimes.each do |opentime|
    %tr
      %td= opentime.bar.name
      %td= opentime.days
      %td= opentime.start
      %td= opentime.finish
      %td= link_to 'Show', opentime
      %td= link_to 'Edit', edit_opentime_path(opentime)
      %td= link_to 'Destroy', opentime, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Opentime', new_opentime_path

app/views/opentimes/new.html.haml
%h1 New opentime
= render 'form'
= link_to 'Back', opentimes_path

app/views/opentimes/show.html.haml
%p#notice= notice
%p
  %b Bar:
  = @opentime.bar.name
%p
  %b Days:
  = @opentime.days
%p
  %b Start:
  = @opentime.start
%p
  %b Finish:
  = @opentime.finish
= link_to 'Edit', edit_opentime_path(@opentime)
|
\#{link_to 'Back', opentimes_path}